### ISSUE TITLE
Feature Request: Using this library with Java 11 (and beyond)

### ISSUE THREAD

**Issue by weiqigao** [altranpt/Robot-Framework-Test-FX-Library#9]
I'm in the process of evaluating the feasibility of using this library with Robot Framework 3.1, the Remote interface, against a Java 11 + OpenJFX 11 modular application.
I understand that this library targets Java 8 and does not work against Java 11 + OpenJFX 11 out of the box.

My first question is: Does this project have a plan to make this library work with Java 11 + OpenJFX 11?

From my experimentation, I've found the following obstacles to using the library with OpenJFX 11:

1. The bundled TestFX version 4.0.10-alpha uses certain OpenJFX internal impl_XXX() methods that were removed since OpenJFX 9.  Upgrading TestFX version to the latest 4.0.15-alpha is required to work around this issue.
2. TestFX version 4.0.15-alpha removed a couple of classes (`org.testfx.service.support.WaitUntilSupport` and `org.testfx.toolkit.PrimaryStageFuture`) from 4.0.10-alpha, and moved a matcher method from one class to another (`org.testfx.matcher.base.NodeMatchers` no longer have a `hasText` method, and the one in `org.testfx.matcher.control.LabeledMatchers` has to be used).  The current code base needs to be modified to compile against 4.0.15-alpha, and the modification is mostly mechanical (I only have to change three classes: `com.altran.gdc.robotframework.testfxlibrary.keywords.Assert`, `com.altran.gdc.robotframework.testfxlibrary.keywords.Misc`, and `com.altran.gdc.robotframework.testfxlibrary.keywords.Wait`).
3. Certain packages are removed from the JDK (this includes JavaFX and JAXB) and have to be added as dependencies.
4. A couple of ancillary tools used by the build (notably `xml-doclet` and `robotframework-maven-plugin`) depends on 'com.sun:tools:1.7` or `tools.jar` file being available in the JDK.  This is no longer the case for JDK 11.  So far I have not found Java 11 compatible replacements for `xml-doclet`.  The latest version of `robotframework-maven-plugin` supports Java 11.
5. There is a reference to `${java.home}/../bin` in the POM file, which I think is no longer correct in Java 11.  There might be other dependencies like this.

It seems to me that issues 1 and 2 can be addressed within the Java 8 environment (as "update TestFX to version 4.0.15-alpha"), after which the resulting TestFXLibrary.jar could be used in a Java 11 + OpenJFX 11 environment.

BTW, this this issues list the best place to ask question about this project?

**Comment by jdagomes** [comment]
Hello @weiqigao,

At the moment we have no plans on upgrading our library to support Java 11 + OpenJFX 11, but feel free to fork the project and modify it as you need.

I'm going to close the issue, any questions you have can be asked in here.

**Comment by weiqigao** [comment]
Thank you @jdagomes for the response.  And thanks to the team for creating this Robot Framework Keywords library for TestFX.

My fork is at https://github.com/weiqigao/Robot-Framework-Test-FX-Library.

**Comment by weiqigao** [comment]
I have committed the changes necessary in my fork to build and use this library in OpenJDK 11 + OpenJFX 11.  I would like to make a release of the library (the jar and the jar with dependencies) to the release tab.  And there are some practical matters that I would like to get the feedback from here:

1. May I continue to use the groupId "com.altran.gdc" for my fork?
2. May I use the version "1.1.0" to signify the breaking changes between the fork and the original library?

If the answer is affirmative to both questions, I would go ahead and make the release.

If you have concerns with this plan, I'm willing to consider any alternative proposals from the maintainers here.
